#!/bin/bash

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

echo -en "Setting up...";
mkdir -p ./nodejs-assets;
rm -rf ./nodejs-assets/nodejs-project;
if [ -f ./nodejs-assets/BUILD_NATIVE_MODULES.txt ]
then
  echo -en " done.\n";
else
  echo '1' > ./nodejs-assets/BUILD_NATIVE_MODULES.txt;
  echo -en " done.\n";
fi

echo -en "Copying source code...";
cp -r ./src/backend ./nodejs-assets;
mv ./nodejs-assets/backend ./nodejs-assets/nodejs-project;
echo -en " done.\n";

echo -en "Installing modules...";
cd ./nodejs-assets/nodejs-project && yarn && cd ../..;
echo -en " done.\n";

echo -en "Updating package-lock.json...";
cp ./nodejs-assets/nodejs-project/yarn.lock ./src/backend/yarn.lock
echo -en " done.\n";
