#!/bin/bash

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

# echo "Building native modules for armeabi-v7a...";
# cd android;
# if [ -f ./gradlew ]
# then
#   ./gradlew nodejs-mobile-react-native:GenerateNodeNativeAssetsListsarmeabi-v7a
# else
#   gradle nodejs-mobile-react-native:GenerateNodeNativeAssetsListsarmeabi-v7a
# fi
# cd ..;
# echo "";

echo -en "Minifying with noderify...";
cd ./nodejs-assets/nodejs-project;
$(npm bin)/noderify \
  --replace.bindings=bindings-noderify-nodejs-mobile \
  --filter=rn-bridge \
  main.js > index.js;
rm main.js;
echo -en " done.\n";


echo -en "Converting to Node 8 with babel...";
./node_modules/.bin/babel ./index.js -o ./main.js

# cd ../..;
# echo -en "Replacing node_modules folder...";
# rm -rf ./nodejs-assets/nodejs-project/node_modules;
# cp -r ./android/build/nodejs-native-assets/nodejs-native-assets-armeabi-v7a/node_modules ./nodejs-assets/nodejs-project;
# echo -en " done.\n";

# cd ./nodejs-assets/nodejs-project;
echo -en "Removing other unused files...";
rm ./index.js;
rm -rf ./actions/;
rm -rf ./utils/;
rm ./babel.config.js;
rm -rf ./patches/;
rm ./yarn.lock;

cd ../../;

echo -en " done.\n";